### ISSUE TITLE
Maintainership for ivcon release

### ISSUE THREAD

**Issue by UltronDestroyer** [ros/ivcon#1]
Hi @isucan, @dirk-thomas, do you mind if I take this package for maintainership? I need it to release pr2_common

**Comment by isucan** [comment]
I would very much appreciate it if you did that! Thank you!

**Comment by UltronDestroyer** [comment]
Alright! I can do that once I am given access to this repo.

**Comment by tfoote** [comment]
@TheDash you're now an admin for this repo.

**Comment by UltronDestroyer** [comment]
Excellent.. excellent
