### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by airballking** [ros/ivcon#4]
Are there plans to release this repository for ```ROS Melodic```?

**Comment by k-okada** [comment]
if no one can release this to melodic, can someone @wjwwood ? @dirk-thomas ? give me write access to this repository and https://github.com/ros-gbp/ivcon-release, so that I can release as a [ROS Orphaned Package Maintainer](http://wiki.ros.org/OrphanedPackage) ?

**Comment by airballking** [comment]
@k-okada Thanks for the initiative!

**Comment by wjwwood** [comment]
If @TheDash cannot maintain it then I will give you access.

**Comment by dirk-thomas** [comment]
@k-okada Done.

**Comment by k-okada** [comment]
ok released, thanks @dirk-thomas 
https://github.com/ros/rosdistro/pull/19050

**Comment by airballking** [comment]
Thanks @k-okada
